-- MySQL Script generated by MySQL Workbench
-- Wed 15 Mar 2017 04:17:49 PM GMT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`communityPresets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`communityPresets` (
  `id` INT NOT NULL,
  `presetName` VARCHAR(30) NULL,
  `plasticName` VARCHAR(6) NULL,
  `speed` INT NULL,
  `temperature` INT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_communityPresets_user_idx` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`myPresets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`myPresets` (
  `user_id` INT NOT NULL,
  `communityPresets_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `communityPresets_id`),
  INDEX `fk_myPreset_communityPresets1_idx` (`communityPresets_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
